# Generated by Django 5.1.15 on 2026-06-25 15:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sector', models.CharField(blank=True, max_length=60)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('day_high', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('day_low', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('volatility', models.FloatField(default=0.01, help_text='Per-tick stdev of returns')),
                ('drift', models.FloatField(default=0.0, help_text='Per-tick mean of returns')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='market.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', '-timestamp'], name='market_pric_instrum_2bb7de_idx')],
            },
        ),
    ]
